### ISSUE TITLE
Unable to run macOS binary

### ISSUE THREAD

**Issue by wimdeblauwe** [sivaprasadreddy/progen#18]
I downloaded version 0.0.6 on my mac. After unzipping, I tried to run it with `./progen`, but then I got this message:

![CleanShot 2024-06-04 at 08 12 40@2x](https://github.com/sivaprasadreddy/progen/assets/1115823/6143a33f-f985-43cb-812b-e24788d39397)

**Comment by sivaprasadreddy** [comment]
@wimdeblauwe The MacOS security is preventing it to run.
Can you please try to install it via `go install github.com/sivaprasadreddy/progen@latest` and try to run?

**Comment by wimdeblauwe** [comment]
The CTRL + click option worked, thanks.
